name: run-orchestrator-2
run-name: Runs orchestrator_2.py
on:
  schedule:
    - cron: '49 12 * * 1'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install flywheel-sdk==18.0.0
      - name: Run Python Script
        run: python orchestrator_2.py
        env:
          FW_API_KEY: ${{ secrets.FW_API_KEY }}
          REDCAP_API_KEY: ${{ secrets.REDCAP_API_KEY }}
          WBHI_BOT_PASSWORD: ${{ secrets.WBHI_BOT_PASSWORD }}
